In [ ]:
#Data Science
#1.Define the problem
#2.Collect the data
#3.EDA - Exploratory Data Analysis
#4.Data Cleaning and pre processing
#5.Feature Engineering
#6.Model Building
#7.Evaluation
#8.Deployment

In [1]:
import pandas as pd
print(pd.__version__)

2.3.3

In [3]:
import json
def load_data(filename):
    with open(filename, 'r') as f:
        data = json.load(f)
    return data

In [4]:
data=load_data('log.json')
print(data)

[{'name': 'Alice', 'rating': '5 ', 'feedback': 'Great product !! ', 'age': '25'}, {'name': 'Bob', 'rating': 'four', 'feedback': 'ok but late Delivery', 'age': '30'}, {'name': ' Charlie', 'rating': 'two', 'feedback': 'BAD EXPERIENCE '}, {'name': 'Diana', 'feedback': 'Loved it!', 'rating': '5', 'age': '28'}, {'name': 'Eve', 'rating': '3.5', 'feedback': 'Average - could be better', 'age': '20'}, {'name': 'Alice', 'rating': '5', 'feedback': 'Great product again!', 'age': '25'}]

In [19]:
df=pd.DataFrame(data)
print(df)

       name rating                   feedback  age
0     Alice     5           Great product !!    25
1       Bob   four       ok but late Delivery   30
2   Charlie    two            BAD EXPERIENCE   NaN
3     Diana      5                  Loved it!   28
4       Eve    3.5  Average - could be better   20
5     Alice      5       Great product again!   25

In [20]:
df

       name rating                   feedback  age
0     Alice     5           Great product !!    25
1       Bob   four       ok but late Delivery   30
2   Charlie    two            BAD EXPERIENCE   NaN
3     Diana      5                  Loved it!   28
4       Eve    3.5  Average - could be better   20
5     Alice      5       Great product again!   25

In [15]:
s=pd.Series([10,15,20,25],index=["shubham","satyarth","satyarth","shubham"])
print(s)
print(s["shubham"])

shubham     10
satyarth    15
satyarth    20
shubham     25
dtype: int64
shubham    10
shubham    25
dtype: int64

In [ ]:
#properties of series
#1 Vectorized operations -- can perform operations on entire series without using loops
#2. homogeneous data -- all elements in a series are of the same data type
#3. Handle Missing values wit NaN -- can represent missing data with NaN (Not a Number)
#4. Mutable values and immutable size -- you can change the values in a series but cannot change its size (number of elements)

In [16]:
s1=pd.Series([1,2,3,4])
s2=pd.Series([5,6,7,8])
print(s1+s2)

0     6
1     8
2    10
3    12
dtype: int64

In [23]:
# print(df.index())
# print(df.columns())
# print(df.dtypes())
print(df.head())
print(df.tail())
print(df.info())
print(df.describe())

       name rating                   feedback  age
0     Alice     5           Great product !!    25
1       Bob   four       ok but late Delivery   30
2   Charlie    two            BAD EXPERIENCE   NaN
3     Diana      5                  Loved it!   28
4       Eve    3.5  Average - could be better   20
       name rating                   feedback  age
1       Bob   four       ok but late Delivery   30
2   Charlie    two            BAD EXPERIENCE   NaN
3     Diana      5                  Loved it!   28
4       Eve    3.5  Average - could be better   20
5     Alice      5       Great product again!   25
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      6 non-null      object
 1   rating    6 non-null      object
 2   feedback  6 non-null      object
 3   age       5 non-null      object
dtypes: object(4)
memory usage: 324.0+ bytes
None
         name rating           feedback age
count       6      6                  6   5
unique      5      5                  6   4
top     Alice      5  Great product !!   25
freq        2      2                  1   2

In [26]:
def load_data(filename):
   data=pd.read_csv(filename)
   return data

data=load_data('sample_data.csv')
df=pd.DataFrame(data)
df

   id          name  age       department  salary
0   1  Aarav Sharma   24      Engineering   75000
1   2    Meera Iyer   29        Marketing   68000
2   3   Rahul Verma   31          Finance   82000
3   4    Priya Nair   27  Human Resources   62000
4   5   Karan Singh   35            Sales   90000
5   6    Ananya Das   23           Design   59000
6   7  Vikram Patel   40       Operations   95000
7   8  Sneha Kapoor   28     Data Science   88000

In [ ]:
#DataFrame Methods
# df.head() -- returns the first n rows of the DataFrame (default is 5)
# df.tail() -- returns the last n rows of the DataFrame (default is 5
# df.info() -- provides a concise summary of the DataFrame, including the number of non-null entries, data types, and memory usage
# df.describe() -- generates descriptive statistics of the DataFrame, including count, mean, standard deviation, minimum, and maximum values for numerical columns
#df.shape -- returns a tuple representing the dimensions of the DataFrame (number of rows, number of columns)
#df.sample() -- returns a random sample of rows from the DataFrame (default is 1 row)
#df.columns -- returns the column names of the DataFrame
#df.unique() -- returns the unique values in a specified column of the DataFrame

In [3]:
# global Air Quality file --by Kaggle.com
df=pd.read_csv('globalAirQuality.csv')
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18000 entries, 0 to 17999
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    18000 non-null  object
 1   country      18000 non-null  object
 2   city         18000 non-null  object
 3   latitude     18000 non-null  float64
 4   longitude    18000 non-null  float64
 5   pm25         18000 non-null  float64
 6   pm10         18000 non-null  float64
 7   no2          18000 non-null  float64
 8   so2          18000 non-null  float64
 9   o3           18000 non-null  float64
 10  co           18000 non-null  float64
 11  aqi          18000 non-null  int64
 12  temperature  18000 non-null  float64
 13  humidity     18000 non-null  float64
 14  wind_speed   18000 non-null  float64
dtypes: float64(11), int64(1), object(3)
memory usage: 2.1+ MB

In [29]:
df.head()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017

In [30]:
df.tail()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [31]:
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [34]:
df.shape

(18000, 15)

In [49]:
df[["city","country","aqi"]]

           city country  aqi
0      New York      US  108
1      New York      US   90
2      New York      US   84
3      New York      US  158
4      New York      US   97
...         ...     ...  ...
17995    Zurich      CH  103
17996    Zurich      CH  105
17997    Zurich      CH  122
17998    Zurich      CH   95
17999    Zurich      CH   88

[18000 rows x 3 columns]

In [46]:
df['aqi']

0        108
1         90
2         84
3        158
4         97
        ...
17995    103
17996    105
17997    122
17998     95
17999     88
Name: aqi, Length: 18000, dtype: int64

In [ ]:
df.loc[0] #loc is used to access a group of rows and columns by labels or a boolean array. It is primarily label based, but may also be used with a boolean array.
df.loc[0:2] #loc includes the last index in the range
df.loc[0:2,["city","country"]]
df.iloc[0:2] #iloc is used to access a group of rows and columns by integer position (index). It is primarily integer position based, but may also be used with a boolean array.
df.iloc[0:2,0:2] #iloc does not include the last index

#rows and columns can also be accessed using the column names and row labels
df.loc[0:2,["city","aqi"]]

#it returns a view of the original DataFrame, so any changes made to the view will affect the original DataFrame. To avoid this, you can use the copy() method to create a copy of the DataFrame before making changes.
subset_df = df.loc[0:2, ["city", "aqi"]].copy

       city  aqi
0  New York  108
1  New York   90
2  New York   84

In [67]:
#Filtering Data
df[ (df['country']== 'US') & (df['aqi']<40)]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
533,2025-11-11 23:25:17.554219,US,Los Angeles,34.052,-118.244,13.750,22.987,9.348,5.963,42.148,1.116,27,23.191,74.563,1.897
15279,2025-11-11 09:25:17.554219,US,San Francisco,37.775,-122.419,13.087,7.782,8.638,3.500,51.672,0.294,26,17.194,33.030,3.104
15543,2025-11-07 09:25:17.554219,US,Chicago,41.878,-87.630,18.307,18.696,6.141,9.165,71.270,0.686,36,14.381,55.736,9.747
16113,2025-11-16 03:25:17.554219,US,Houston,29.760,-95.370,17.716,20.122,15.497,6.585,24.002,0.370,38,8.189,89.883,2.436
16169,2025-11-18 11:25:17.554219,US,Houston,29.760,-95.370,18.189,39.520,10.559,7.224,52.485,1.052,39,35.112,63.921,5.927

In [68]:
#Query
df.query('country == "US" and aqi < 40')

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
533,2025-11-11 23:25:17.554219,US,Los Angeles,34.052,-118.244,13.750,22.987,9.348,5.963,42.148,1.116,27,23.191,74.563,1.897
15279,2025-11-11 09:25:17.554219,US,San Francisco,37.775,-122.419,13.087,7.782,8.638,3.500,51.672,0.294,26,17.194,33.030,3.104
15543,2025-11-07 09:25:17.554219,US,Chicago,41.878,-87.630,18.307,18.696,6.141,9.165,71.270,0.686,36,14.381,55.736,9.747
16113,2025-11-16 03:25:17.554219,US,Houston,29.760,-95.370,17.716,20.122,15.497,6.585,24.002,0.370,38,8.189,89.883,2.436
16169,2025-11-18 11:25:17.554219,US,Houston,29.760,-95.370,18.189,39.520,10.559,7.224,52.485,1.052,39,35.112,63.921,5.927

In [69]:
aqi_val = 100
df.query("aqi >100 & temperature > 30") [["city", "aqi"]]
df.query("aqi > @aqi_val & temperature > 30") [["city", "aqi"]]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [ ]:
# Handle Missing Values

# ·isnull( ) / isna()

# ·isnull( ).sum()

# ·dropna( )

# ·fillna(value)

# ·ffill()

# ·bfill()

In [ ]:
import pandas as pd
df=pd.read_csv('messy_sample_data.csv')
df

,id,name,age,department,salary,city,join_date,email,performance_score
0,1,Aarav Sharma,24.0,Engineering,75000.0,Delhi,2022-01-15,aarav.sharma@example.com,8.7
1,2,Meera Iyer,NaN,Marketing,68000.0,Mumbai,2021-07-10,meera.iyer@example.com,9.1
2,3,Rahul Verma,31.0,Finance,NaN,Bengaluru,2020-03-22,rahul.verma@example.com,NaN
3,4,Priya Nair,27.0,Human Resources,62000.0,NaN,2023-11-01,priya.nair@example.com,7.8
4,5,Karan Singh,35.0,Sales,90000.0,Jaipur,NaN,karan.singh@example.com,8.4
5,6,Ananya Das,23.0,Design,59000.0,Kolkata,2022-09-18,NaN,NaN
6,7,Vikram Patel,40.0,Operations,95000.0,Ahmedabad,2021-01-05,vikram.patel@example.com,9.3
7,8,Sneha Kapoor,28.0,Data Science,88000.0,Pune,2023-05-30,sneha.kapoor@example.com,8.9
8,9,Imran Khan,NaN,Support,54000.0,Hyderabad,2022-12-12,imran.khan@example.com,6.5
9,10,Neha Joshi,30.0,Product,NaN,Chennai,2024-02-20,neha.joshi@example.com,8.1
10,11,Raj Malhotra,38.0,Engineering,101000.0,NaN,2020-08-14,raj.malhotra@example.com,9.0
11,12,Simran Kaur,26.0,Marketing,67000.0,Lucknow,2023-04-09,simran.kaur@example.com,NaN

In [ ]:
df.isnull()

,id,name,age,department,salary,city,join_date,email,performance_score
0,False,False,False,False,False,False,False,False,False
1,False,False,True,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,True
3,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,True,False,False
5,False,False,False,False,False,False,False,True,True
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,True,False,False,False,False,False,False
9,False,False,False,False,True,False,False,False,False
10,False,False,False,False,False,True,False,False,False
11,False,False,False,False,False,False,False,False,True

In [ ]:
df.isnull().sum()

id                   0
name                 0
age                  2
department           0
salary               2
city                 2
join_date            1
email                1
performance_score    3
dtype: int64

In [6]:
df.dropna()
df.dropna(axis=1) #drop columns with missing values

    id          name       department
0    1  Aarav Sharma      Engineering
1    2    Meera Iyer        Marketing
2    3   Rahul Verma          Finance
3    4    Priya Nair  Human Resources
4    5   Karan Singh            Sales
5    6    Ananya Das           Design
6    7  Vikram Patel       Operations
7    8  Sneha Kapoor     Data Science
8    9    Imran Khan          Support
9   10    Neha Joshi          Product
10  11  Raj Malhotra      Engineering
11  12   Simran Kaur        Marketing

In [7]:
df.fillna(0) #fill missing values with 0

,id,name,age,department,salary,city,join_date,email,performance_score
0,1,Aarav Sharma,24.0,Engineering,75000.0,Delhi,2022-01-15,aarav.sharma@example.com,8.7
1,2,Meera Iyer,0.0,Marketing,68000.0,Mumbai,2021-07-10,meera.iyer@example.com,9.1
2,3,Rahul Verma,31.0,Finance,0.0,Bengaluru,2020-03-22,rahul.verma@example.com,0.0
3,4,Priya Nair,27.0,Human Resources,62000.0,0,2023-11-01,priya.nair@example.com,7.8
4,5,Karan Singh,35.0,Sales,90000.0,Jaipur,0,karan.singh@example.com,8.4
5,6,Ananya Das,23.0,Design,59000.0,Kolkata,2022-09-18,0,0.0
6,7,Vikram Patel,40.0,Operations,95000.0,Ahmedabad,2021-01-05,vikram.patel@example.com,9.3
7,8,Sneha Kapoor,28.0,Data Science,88000.0,Pune,2023-05-30,sneha.kapoor@example.com,8.9
8,9,Imran Khan,0.0,Support,54000.0,Hyderabad,2022-12-12,imran.khan@example.com,6.5
9,10,Neha Joshi,30.0,Product,0.0,Chennai,2024-02-20,neha.joshi@example.com,8.1
10,11,Raj Malhotra,38.0,Engineering,101000.0,0,2020-08-14,raj.malhotra@example.com,9.0
11,12,Simran Kaur,26.0,Marketing,67000.0,Lucknow,2023-04-09,simran.kaur@example.com,0.0

In [10]:
df["age"].fillna(df["age"].mean()) #fill missing values in Age column with mean age

0     24.0
1     30.2
2     31.0
3     27.0
4     35.0
5     23.0
6     40.0
7     28.0
8     30.2
9     30.0
10    38.0
11    26.0
Name: age, dtype: float64

In [12]:
cleaned_data=df.copy()
cleaned_data["age"].fillna(cleaned_data["age"].mean())

0     24.0
1     30.2
2     31.0
3     27.0
4     35.0
5     23.0
6     40.0
7     28.0
8     30.2
9     30.0
10    38.0
11    26.0
Name: age, dtype: float64

In [14]:
cleaned_data=df.ffill() #forward fill - fills missing values with the last valid observation
cleaned_data=df.bfill() #backward fill - fills missing values with the next valid observation

In [15]:
#Handles Duplicates Valuse
df.duplicated() #returns a boolean Series indicating whether each row is a duplicate of a previous row

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
dtype: bool

In [4]:
df["temperature"].fillna(df["temperature"].mean()) #fill missing values in temperature column with mean value of that column

0        18.504
1         5.838
2        31.833
3        23.140
4        13.632
          ...
17995     7.079
17996    28.734
17997    21.951
17998    24.042
17999     8.529
Name: temperature, Length: 18000, dtype: float64

In [18]:
df2=df.copy()
df2["longitude"]=df2["longitude"].fillna(0).astype("int64").copy()
print(df2.dtypes)
df2

timestamp       object
country         object
city            object
latitude       float64
longitude        int64
pm25           float64
pm10           float64
no2            float64
so2            float64
o3             float64
co             float64
aqi              int64
temperature    float64
humidity       float64
wind_speed     float64
dtype: object

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [22]:
date_str=pd.to_datetime("2026-11-12")
print(type(date_str))
data=df
data["timestamp"]=pd.to_datetime(data["timestamp"])

<class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [ ]:
#strings method
# str.lower() -- converts all characters in a string to lowercase
# str.upper() -- converts all characters in a string to uppercase
# str.title() -- converts the first character of each word to uppercase and the rest to lowercase
#str.captalize() -- converts the first character of a string to uppercase and the rest to lowercase
#st.strip() -- removes leading and trailing whitespace from a string
#str.split() -- splits a string into a list of substrings based on a specified delimiter
#str.contains(val,case=False) -- checks if a string contains a specified substring and returns a boolean value

In [ ]:
#Data Transformation
# apply() -- applies a function along an axis of the DataFrame (e.g., applying a function to each column or row)
# map() -- applies a function to each element of a Series and returns a new Series with the transformed values
# assign() -- assigns new columns to a DataFrame based on the results of applying a function to existing columns
#replace(old,new) -- replaces occurrences of a specified value (old) with another value (new) in the DataFrame