In [ ]:
#Data Science
#1.Define the problem
#2.Collect the data
#3.EDA - Exploratory Data Analysis
#4.Data Cleaning and pre processing
#5.Feature Engineering
#6.Model Building
#7.Evaluation
#8.Deployment

In [2]:
import pandas as pd
print(pd.__version__)

2.3.3

In [3]:
import json
def load_data(filename):
    with open(filename, 'r') as f:
        data = json.load(f)
    return data

In [4]:
data=load_data('log.json')
print(data)

[{'name': 'Alice', 'rating': '5 ', 'feedback': 'Great product !! ', 'age': '25'}, {'name': 'Bob', 'rating': 'four', 'feedback': 'ok but late Delivery', 'age': '30'}, {'name': ' Charlie', 'rating': 'two', 'feedback': 'BAD EXPERIENCE '}, {'name': 'Diana', 'feedback': 'Loved it!', 'rating': '5', 'age': '28'}, {'name': 'Eve', 'rating': '3.5', 'feedback': 'Average - could be better', 'age': '20'}, {'name': 'Alice', 'rating': '5', 'feedback': 'Great product again!', 'age': '25'}]

In [19]:
df=pd.DataFrame(data)
print(df)

       name rating                   feedback  age
0     Alice     5           Great product !!    25
1       Bob   four       ok but late Delivery   30
2   Charlie    two            BAD EXPERIENCE   NaN
3     Diana      5                  Loved it!   28
4       Eve    3.5  Average - could be better   20
5     Alice      5       Great product again!   25

In [20]:
df

       name rating                   feedback  age
0     Alice     5           Great product !!    25
1       Bob   four       ok but late Delivery   30
2   Charlie    two            BAD EXPERIENCE   NaN
3     Diana      5                  Loved it!   28
4       Eve    3.5  Average - could be better   20
5     Alice      5       Great product again!   25

In [15]:
s=pd.Series([10,15,20,25],index=["shubham","satyarth","satyarth","shubham"])
print(s)
print(s["shubham"])

shubham     10
satyarth    15
satyarth    20
shubham     25
dtype: int64
shubham    10
shubham    25
dtype: int64

In [ ]:
#properties of series
#1 Vectorized operations -- can perform operations on entire series without using loops
#2. homogeneous data -- all elements in a series are of the same data type
#3. Handle Missing values wit NaN -- can represent missing data with NaN (Not a Number)
#4. Mutable values and immutable size -- you can change the values in a series but cannot change its size (number of elements)

In [16]:
s1=pd.Series([1,2,3,4])
s2=pd.Series([5,6,7,8])
print(s1+s2)

0     6
1     8
2    10
3    12
dtype: int64

In [23]:
# print(df.index())
# print(df.columns())
# print(df.dtypes())
print(df.head())
print(df.tail())
print(df.info())
print(df.describe())

       name rating                   feedback  age
0     Alice     5           Great product !!    25
1       Bob   four       ok but late Delivery   30
2   Charlie    two            BAD EXPERIENCE   NaN
3     Diana      5                  Loved it!   28
4       Eve    3.5  Average - could be better   20
       name rating                   feedback  age
1       Bob   four       ok but late Delivery   30
2   Charlie    two            BAD EXPERIENCE   NaN
3     Diana      5                  Loved it!   28
4       Eve    3.5  Average - could be better   20
5     Alice      5       Great product again!   25
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      6 non-null      object
 1   rating    6 non-null      object
 2   feedback  6 non-null      object
 3   age       5 non-null      object
dtypes: object(4)
memory usage: 324.0+ bytes
None
         name rating           feedback age
count       6      6                  6   5
unique      5      5                  6   4
top     Alice      5  Great product !!   25
freq        2      2                  1   2

In [25]:
def load_data(filename):
   data=pd.read_csv(filename)
   return data

data=load_data('sample_data.csv')
df=pd.DataFrame(data)
df

   id          name  age       department  salary
0   1  Aarav Sharma   24      Engineering   75000
1   2    Meera Iyer   29        Marketing   68000
2   3   Rahul Verma   31          Finance   82000
3   4    Priya Nair   27  Human Resources   62000
4   5   Karan Singh   35            Sales   90000
5   6    Ananya Das   23           Design   59000
6   7  Vikram Patel   40       Operations   95000
7   8  Sneha Kapoor   28     Data Science   88000

In [ ]:
#DataFrame Methods
# df.head() -- returns the first n rows of the DataFrame (default is 5)
# df.tail() -- returns the last n rows of the DataFrame (default is 5
# df.info() -- provides a concise summary of the DataFrame, including the number of non-null entries, data types, and memory usage
# df.describe() -- generates descriptive statistics of the DataFrame, including count, mean, standard deviation, minimum, and maximum values for numerical columns
#df.shape -- returns a tuple representing the dimensions of the DataFrame (number of rows, number of columns)
#df.sample() -- returns a random sample of rows from the DataFrame (default is 1 row)
#df.columns -- returns the column names of the DataFrame
#df.unique() -- returns the unique values in a specified column of the DataFrame